---
title: "Chapter 1 Intro"
author: "Rchemist"
format: html
editor: visual
---

## Why R?

-   개인적인 경험으로 봤을 때, `R`은 다른 언어보다 간단하고 쉽게 해낼 수 있는 것들이 많습니다.

    `R`은 `Python`과 같은 다른 프로그래밍 언어와 비슷합니다. `R`을 잘 배워두면 나중에 다른 언어를 배울 때도 더 빠르게 배울 수 있습니다. 실제로 저 또한 `R`로 데이터 분석을 처음 접하였습니다.

    실제로 Java나 C와 같은 다른 프로그래밍 언어를 접해본 사람 `R`을 배워보면 얼마나 쉬운 언어인지 알 수 있습니다.

-   `R`은 무료입니다. `R`과 함께 사용하는 RStudio 라는 통합분석환경(IDE) 역시 무료로 사용할 수 있습니다. 그렇기 때문에 데이터 분석에서 Stata나 SAS 보다 접근성이 좋다고 할 수 있습니다.

-   `R`은 유연한 언어입니다. SPSS 나 Excel과는 달리 내가 입력하는 코드에 따라 결과물의 형태를 자유자재로 바꿀 수 있습니다.

-   RStudio 자체가 굉장히 훌륭한 데이터 분석 플랫폼입니다. Python의 jupyter notebook, Spyder 같은 플랫폼보다 더욱 잘 만들어진 IDE 입니다.

## Python이 아닌 이유?

-   우선 `Python`은 온전히 데이터 분석을 위한 언어라고 할 수 없습니다. `Python`은 프로그래밍 언어로써, 데이터 분석 역시 가능하지만, 개발과 같은 좀더 일반적인 용도에 최적화된 프로그래밍 언어입니다. 그렇다 보니 데이터 분석이라는 목적에서 봤을 때, `R`을 배우는 것이 더욱 효율적입니다.

-   `Python이` `R`에 비해 더 복잡합니다. `R`보다 `Python`이 알아야 할 코드들이 더 많고, 같은 기능을 하는 코드를 짜는 데 `Python`이 더 시간이 많이 소요됩니다.

-   그렇다 보니 `Python`보다 `R`을 사용하는 것이 데이터를 핸들링 (data wrangling 또는 data cleansing) 하기 더욱 편리합니다.
